"use client";

import React, { useState, useEffect, useCallback, useMemo } from "react";
import { sweep } from "@/lib/api";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ReferenceLine,
  ResponsiveContainer,
  Label,
} from "recharts";

type SweepPoint = {
  range_km: number;
  condition: string;
  dc_power_kw: number;
  elec_input_kw: number;
  system_eff_pct: number;
  fuel_saved_l_day: number;
};

type PivotRow = Record<string, number>;

// Ranges returned by backend
const RANGES_KM = [0.5, 1.0, 2.0, 3.0, 5.0, 7.5, 10.0];

// Use-case presets
type SweepPreset = {
  id: string;
  label: string;
  sublabel: string;
  range_km: number;
  power_kw: number;
  condition: string;
  preferredMode: "laser" | "microwave";
  regimeIdx: number; // 0–3
  note: string;
  nearField?: boolean; // range below chart minimum (0.5 km)
};

const SWEEP_PRESETS: SweepPreset[] = [
  {
    id: "shipboard",
    label: "Shipboard Drone",
    sublabel: "30–50 m · 1 kW · Clear",
    range_km: 0.04,
    power_kw: 1,
    condition: "clear",
    preferredMode: "laser",
    regimeIdx: 0,
    nearField: true,
    note: "Operates in the near-field zone — off the left edge of this chart. Beam radius < 0.1 mm. Geometric loss is negligible. Dominant losses: PA (~40%) + PV conversion (~43% actual). Best-case system efficiency: 20–35%.",
  },
  {
    id: "drone_isr",
    label: "Drone ISR",
    sublabel: "300 m · 0.5 kW · Clear",
    range_km: 0.3,
    power_kw: 0.5,
    condition: "clear",
    preferredMode: "laser",
    regimeIdx: 0,
    nearField: true,
    note: "Below chart minimum (300 m). Still near-field for laser. Beam radius ≈ 0.7 mm — complete capture. DARPA FENCE and PowerLight PTROL-UAS demonstrated this exact scenario. Turbulence at 300 m is minimal. Expected sys eff: 18–25%.",
  },
  {
    id: "sof_outpost",
    label: "SOF Outpost",
    sublabel: "800 m · 3 kW · Clear",
    range_km: 0.8,
    power_kw: 3,
    condition: "clear",
    preferredMode: "laser",
    regimeIdx: 1,
    note: "Short tactical range — laser beam is 2–3 mm wide. Turbulence begins to matter but is manageable (Strehl ~15–30% at 800 m daytime). Primary requirement: zero acoustic/thermal signature. Generator alternative: 70 dB noise, FLIR-visible.",
  },
  {
    id: "remote_sensor",
    label: "Remote Sensor",
    sublabel: "1 km · 0.1 kW · Rain",
    range_km: 1.0,
    power_kw: 0.1,
    condition: "rain",
    preferredMode: "microwave",
    regimeIdx: 1,
    note: "Fixed geometry, all-weather. Microwave at 1 km in rain: 0.44 dB/km attenuation → negligible. Beam 62 m wide vs fixed rectenna — low efficiency, but for 100 W sensors the absolute power requirement is small. Eliminates resupply exposure entirely.",
  },
  {
    id: "counter_uas",
    label: "Counter-UAS",
    sublabel: "1 km · 10 kW · Clear",
    range_km: 1.0,
    power_kw: 10,
    condition: "clear",
    preferredMode: "laser",
    regimeIdx: 1,
    note: "Power delivery to a forward C-UAS emitter without exposed cables or a generator at the weapon site. At 1 km clear sky, laser delivers 1–2 kW to the C-UAS weapon. Source remains at a protected standoff position. Weapon can be repositioned without re-running power infrastructure.",
  },
  {
    id: "fob_power",
    label: "FOB Power",
    sublabel: "2 km · 15 kW · Clear",
    range_km: 2.0,
    power_kw: 15,
    condition: "clear",
    preferredMode: "laser",
    regimeIdx: 1,
    note: "Primary Aether mission scenario. Turbulence is the dominant loss at 2 km (Strehl 3–15% daytime). In clear sky: 6–15% system efficiency. Adaptive optics recovers +4 to +10 dB. Annual value: ~$3.4M/yr per FOB (fuel + convoy costs). Payback: 12–18 months at $750k system cost.",
  },
  {
    id: "battlefield_relay",
    label: "Battlefield Relay",
    sublabel: "5 km · 5 kW · Smoke",
    range_km: 5.0,
    power_kw: 5,
    condition: "smoke",
    preferredMode: "laser",
    regimeIdx: 2,
    note: "Direct link in smoke at 5 km: 40 dB loss → ~0 W delivered. Relay-regeneration (5×1 km hops): each hop loses 8 dB, regenerated by EDFA relay drone. End-to-end: 3–5% efficiency → 300–500 W delivered. This is the core Aether IP — no prior art for terrestrial laser power relay chains.",
  },
];

function regimeIndexForRange(range_km: number): number {
  if (range_km <= 0.5) return 0;
  if (range_km <= 2.0) return 1;
  if (range_km <= 5.0) return 2;
  return 3;
}

const CONDITION_META: Record<string, { color: string; label: string; dash?: string }> = {
  clear:         { color: "#4ade80", label: "Clear sky" },
  haze:          { color: "#facc15", label: "Haze", dash: "5 5" },
  smoke:         { color: "#f97316", label: "Smoke/battlefield", dash: "8 4" },
  rain:          { color: "#60a5fa", label: "Rain (heavy)", dash: "4 4" },
  drizzle:       { color: "#a78bfa", label: "Drizzle", dash: "5 5" },
  light_rain:    { color: "#818cf8", label: "Light rain", dash: "6 4" },
  moderate_rain: { color: "#3b82f6", label: "Moderate rain", dash: "4 4" },
  heavy_rain:    { color: "#1d4ed8", label: "Heavy rain", dash: "2 4" },
};

function pivotData(data: SweepPoint[]): { rows: PivotRow[]; conditions: string[] } {
  const byRange: Record<number, PivotRow> = {};
  const conditions = new Set<string>();
  for (const pt of data) {
    if (!byRange[pt.range_km]) byRange[pt.range_km] = { range_km: pt.range_km };
    if (pt.system_eff_pct != null && !isNaN(pt.system_eff_pct)) {
      byRange[pt.range_km][pt.condition] = parseFloat(pt.system_eff_pct.toFixed(3));
    }
    conditions.add(pt.condition);
  }
  return {
    rows: Object.values(byRange).sort((a, b) => a.range_km - b.range_km),
    conditions: Array.from(conditions),
  };
}

function SectionHeader({ children }: { children: React.ReactNode }) {
  return (
    <div className="text-xs font-medium uppercase tracking-wider mb-4" style={{ color: "var(--text-subtle)" }}>
      {children}
    </div>
  );
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div
      className={`rounded-xl p-5 ${className}`}
      style={{ background: "var(--surface)", border: "1px solid var(--border)" }}
    >
      {children}
    </div>
  );
}

function InlineCode({ children }: { children: React.ReactNode }) {
  return (
    <code className="font-mono text-xs px-1.5 py-0.5 rounded" style={{ background: "var(--surface-2)", color: "#fb923c" }}>
      {children}
    </code>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Regime cards
// ─────────────────────────────────────────────────────────────────────────────

const REGIMES = [
  {
    range: "0 – 500 m",
    label: "Near-field / High-efficiency",
    color: "#22c55e",
    badge: "Best physics",
    problems: [
      "Beam tightly confined — minimal geometric loss for laser",
      "Microwave already in far-field beyond 13 m (Rayleigh distance for 0.83 m array at 5.8 GHz)",
      "Dominant losses: PA efficiency (~40%) and PV conversion (~43% actual, after temperature derating)",
    ],
    math: [
      "Laser at 300 m, 0.3 m aperture, 1070 nm: beam radius = (λ/πw₀)·R = 0.7 mm → receiver captures 100% of beam",
      "Microwave at 300 m: beam radius = (λ/D)·R = 62 mrad × 300 m = 18.6 m → receiver at 2 m² captures 2/(π·18.6²) = 0.18% of beam",
      "System efficiency ceiling (laser): ~25–35% (wall-plug → photon → PV conversion chain)",
      "System efficiency ceiling (microwave): ~2–4% at 300 m (beam spread dominates)",
    ],
    solutions: [
      { fix: "InP monochromatic PV cells", gain: "+12 points efficiency (43% actual → 55% InP)" },
      { fix: "Larger TX aperture (2× diameter)", gain: "+6 dB geometric capture = 4× more power at receiver" },
      { fix: "GaN PA next-gen (65%)", gain: "+10 points wall-plug efficiency vs standard 55%" },
    ],
    applications: "Shipboard drone charging, SOF base adjacent power, laboratory demo scenarios",
  },
  {
    range: "500 m – 2 km",
    label: "Tactical close range",
    color: "#facc15",
    badge: "Primary FOB window",
    problems: [
      "Laser maintains good beam tightness — beam radius 2–10 mm at 2 km (0.3 m aperture)",
      "Microwave beam radius = 110 m at 2 km — impractical receiver size for mobile deployment",
      "Turbulence begins degrading laser Strehl ratio (Cn² ~10⁻¹⁴ m⁻²/³ typical daytime)",
      "Pointing jitter at 5 µrad = 10 mm offset at 2 km — significant vs 10 mm beam",
    ],
    math: [
      "Laser beam radius at 2 km (1070 nm, 0.3 m aperture): R·λ/(π·w₀) = 2000 × 3.57 µm / (π × 0.15) = 15 mm",
      "Fried parameter r₀ (daytime, Cn² = 10⁻¹⁴): r₀ = 0.185(λ⁶/Cn²·L)^(3/5) = 12 cm at 2 km",
      "Strehl ratio = exp[−(D/r₀)^(5/3)] = exp[−(0.3/0.12)^(5/3)] = exp[−3.4] = 3.3%",
      "Turbulence loss = −14.8 dB at 2 km daytime — the dominant loss mechanism",
      "Microwave at 2 km: beam area = π × 110² = 38,000 m², receiver captures 2/38,000 = 5.3 × 10⁻⁵",
      "Microwave far-field geometric loss = −42.7 dB at 2 km — fundamentally impractical",
    ],
    solutions: [
      { fix: "Adaptive optics (Shack-Hartmann + DM)", gain: "2.5–10× Strehl → +4 to +10 dB at 2 km" },
      { fix: "Longer wavelength (1550 nm eye-safe)", gain: "40% lower smoke loss; mature EDFA telecom components" },
      { fix: "Phased array beam forming (microwave)", gain: "Electronically steerable beam — needed for any practical microwave WPT beyond 500 m" },
      { fix: "Larger receiver aperture (0.5 → 1 m²)", gain: "+3 dB collection for laser; negligible for microwave at this range" },
    ],
    applications: "FOB power supply, remote sensor networks, battlefield relay origin point",
  },
  {
    range: "2 – 5 km",
    label: "Extended tactical range",
    color: "#f97316",
    badge: "Relay zone",
    problems: [
      "Laser turbulence loss becomes severe — Strehl can drop to 1% without AO",
      "In smoke (8 dB/km at 1070 nm): 40 dB loss over 5 km → 1 part in 10,000 delivered",
      "Rain blocks laser; microwave survives rain but beam is 300 m+ wide — useless without multi-km rectenna",
      "Single-hop WPT at 5 km in any degraded condition is effectively zero power delivered",
    ],
    math: [
      "Laser turbulence Strehl at 5 km (Cn² = 10⁻¹⁴): r₀ = 4.3 cm, Strehl = exp[−(0.3/0.043)^(5/3)] = 0.0003 (−35 dB)",
      "Smoke attenuation (1070 nm) at 5 km: 8 dB/km × 5 = 40 dB → 10⁻⁴ transmission",
      "Rain attenuation (5.8 GHz, 50 mm/hr): 0.44 dB/km × 5 km = 2.2 dB → tolerable for microwave",
      "Microwave beam radius at 5 km: 5000 × 62 mrad = 310 m → captures 2/π·310² = 6.6 × 10⁻⁶ → −52 dB",
      "1550 nm smoke attenuation: 4.8 dB/km × 5 km = 24 dB → still severe but 16 dB better than 1070 nm",
      "Relay chain (5 × 1 km in smoke): 8 dB/segment × 5 = 40 dB gross, regenerated at each hop",
      "Relay chain output (assuming 15% conversion loss/relay, 5 relays): 0.85^5 × 0.12 ≈ 5.4% end-to-end",
    ],
    solutions: [
      { fix: "Relay-regeneration architecture (core Aether IP)", gain: "5 km in smoke: 0W direct → 300–500W via 5×1km relay chain" },
      { fix: "1550 nm wavelength", gain: "−40% smoke extinction per km: 4.8 vs 8 dB/km (saves ~16 dB over 5 km)" },
      { fix: "Adaptive optics at source", gain: "+10 dB turbulence recovery at 5 km (wavefront pre-compensation)" },
      { fix: "Autonomous drone relay nodes", gain: "EDFA retransmit at each hop; drone hovers at optimal altitude above turbulent boundary layer" },
    ],
    applications: "Extended FOB chains, contested logistics corridors, relay-regeneration demonstration case",
  },
  {
    range: "5 – 10 km",
    label: "Long-range / relay required",
    color: "#818cf8",
    badge: "Multi-hop only",
    problems: [
      "Single-hop direct link is physics-limited: turbulence Strehl approaches 0.01% in any real atmosphere",
      "Clear-sky only, dawn/dusk (low Cn²): single-hop laser can deliver limited power but efficiency < 2%",
      "Microwave at 10 km: beam 620 m wide, impossible to use with any practical receiver",
      "Weather resilience requires multi-hop relay chain with per-segment regeneration",
    ],
    math: [
      "Laser at 10 km clear sky, 0.3 m aperture: beam radius = 30 mm, captures well IF Strehl is maintained",
      "Strehl at 10 km (Cn² = 10⁻¹⁴): r₀ = 2.2 cm, Strehl = exp[−(0.3/0.022)^(5/3)] < 10⁻⁶ → turbulence-limited",
      "With adaptive optics (AO): Strehl recovers to ~0.1–1% at 10 km depending on bandwidth",
      "10×1km relay chain in clear sky: each hop 18% eff., regenerated; end-to-end = 0.82^(overhead) × 0.18 ≈ 7%",
      "10×1km relay chain in smoke: 8 dB/hop recovered at each node; end-to-end ≈ 3–5%",
      "Power budget: 10 kW source → 300–700W at 10 km via relay (vs ~1W direct in smoke)",
      "Drone relay cost: ~$50k/node COTS + ~$5k EDFA amplifier → 10-hop system: ~$550k",
    ],
    solutions: [
      { fix: "Multi-hop relay chain with regeneration", gain: "10 km becomes 10× 1 km links — physics reset at each node" },
      { fix: "High-altitude relay drone (HAP/drone)", gain: "Above turbulent boundary layer (>2 km AGL): Cn² drops 10–100×" },
      { fix: "Coherent beam combining", gain: "Multiple smaller TX arrays combined coherently: same aperture gain, lower mass per unit" },
      { fix: "Wavelength optimization (1550 nm)", gain: "Telecom-grade EDFA amplifiers at relay nodes: $2–5k vs $50k+ for 1070 nm" },
    ],
    applications: "Cross-valley logistics, extended FOB supply chains, future LEO stepping stone",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Loss mechanism cards
// ─────────────────────────────────────────────────────────────────────────────

const LOSS_MECHANISMS = [
  {
    title: "Geometric Beam Spreading",
    icon: "⌾",
    color: "#f97316",
    laser: "Minimal at tactical range. Beam radius = R·λ/(π·w₀). At 2 km with 0.3 m aperture: 15 mm — sub-1 dB capture loss. Dominant only at 10 km+ (beam reaches 30 mm).",
    microwave: "Catastrophic. Beam radius = R·(λ/D). At 2 km with 0.83 m array: 110 m beam vs 2 m² receiver → captures 5 × 10⁻⁵ of power (−43 dB). Scales as R². Halving range = 4× power.",
    formula: "P_rx / P_tx = (A_rx) / (π · (R · θ)²)  where  θ = λ/D",
    fix: "Laser: already near-diffraction-limited. Larger aperture helps. Microwave: phased array is the only path — electrically steerable, large effective aperture.",
  },
  {
    title: "Atmospheric Absorption & Scattering",
    icon: "◈",
    color: "#60a5fa",
    laser: "Clear: 0.02–0.07 dB/km (negligible). Haze: 0.5–2 dB/km. Smoke (1070 nm): 8 dB/km — 40 dB over 5 km. Rain blocks completely beyond 500 m (fog hard-block). Smoke is the mission killer.",
    microwave: "Rain: 0.44 dB/km at 50 mm/hr (5.8 GHz). Even at 10 km in heavy rain: 4.4 dB total — ~64% power loss (leaves 36% of transmitted power). Fog: transparent. Smoke: nearly transparent. Microwave wins all-weather at short range.",
    formula: "P_atm = P_tx · 10^(−α·R / 10)  where  α [dB/km] = k · I^β  (ITU-R P.838-3)",
    fix: "1550 nm wavelength cuts smoke extinction 40% vs 1070 nm. Relay-regeneration defeats smoke at any range — each 1 km hop only loses 8 dB, then regenerated. Rain: switch to microwave at short range.",
  },
  {
    title: "Turbulence (Laser Only)",
    icon: "∿",
    color: "#a78bfa",
    laser: "Thermal fluctuations in the air create refractive index variations (Cn²). The beam breaks up and wanders. Fried parameter r₀ characterizes coherence. Strehl ratio = exp[−(D/r₀)^(5/3)]. At 2 km daytime: Strehl ≈ 3% (−15 dB).",
    microwave: "Negligible. Millimeter waves are unaffected by optical turbulence. Refractive index variations at 5.8 GHz are 10⁷× smaller than at 1070 nm. Only ionospheric scintillation matters at GHz frequencies — irrelevant at tactical ranges.",
    formula: "r₀ = 0.185 · (λ⁶ / Cn² · R)^(3/5)   Strehl = exp[−(D/r₀)^(5/3)]",
    fix: "Adaptive optics: Shack-Hartmann wavefront sensor + MEMS deformable mirror. 2–10× Strehl improvement demonstrated. Pre-compensation: measure wavefront, conjugate-phase the TX beam. Night: Cn² drops 10–100× (cooler, stable air). Dawn/dusk: best performance window.",
  },
  {
    title: "Conversion Efficiency Chain",
    icon: "⚡",
    color: "#22c55e",
    laser: "Wall-plug → photon: 40–60% (diode-pumped fiber laser). Photon → DC (PV): 50% base efficiency for monochromatic GaAs PV, ×0.86 temperature derating = 43% actual. InP monochromatic cells: 55% (2023, Sandia). Total chain: wall-plug → DC ~6–15% typical deployed.",
    microwave: "Wall-plug → RF (GaN PA): 50–60%. RF → DC (rectenna): 85% at full power density, 52% at low power density (<25 mW/cm²). At long range, power density at rectenna is micro-watts → rectenna efficiency collapses to 10–20%.",
    formula: "η_sys = η_wallplug × η_atm × η_geometric × η_conversion\n(each term ≤ 1; all multiplied together)",
    fix: "InP monochromatic PV: 55% conversion efficiency (commercializing 2025–2026). High-power-density rectenna: maintain >1 W/cm² for 85% rectification — requires beam tight enough at range or multi-element focusing array.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Condition deep dive
// ─────────────────────────────────────────────────────────────────────────────

const CONDITION_DEEP_DIVE = [
  {
    cond: "clear",
    title: "Clear Sky",
    color: "#4ade80",
    laser: "Best case. ~0.04 dB/km absorption. Turbulence is the main variable — 10× difference between dawn (low Cn²) and midday (high convection). At 2 km: 6–15% system efficiency depending on time of day.",
    microwave: "Geometric divergence dominates entirely. No atmospheric help. Efficiency at 2 km: <0.5%.",
    decision: "Always prefer laser in clear sky beyond 200 m. Microwave only below 200 m where near-field geometry allows sufficient capture.",
  },
  {
    cond: "smoke",
    title: "Smoke / Battlefield Aerosols",
    color: "#f97316",
    laser: "Mission killer for direct link. 8 dB/km at 1070 nm, 4.8 dB/km at 1550 nm. At 5 km in smoke: 40 dB loss → 1 part in 10,000 reaches receiver. Hard physics limit — no amount of power overcomes this on a direct link.",
    microwave: "Near-transparent. Military smoke particles are 1–100 µm — much smaller than 52 mm wavelength (5.8 GHz). Attenuation < 0.01 dB/km. Microwave passes through smoke as if clear. Range still limited by geometric spread but atmosphere is not the problem.",
    decision: "Smoke = switch to microwave for short links, or relay-regeneration for long links. 1550 nm laser with relay chain is optimal for multi-km smoke traversal — each 1 km hop degrades only 4.8 dB, then regenerated by EDFA relay.",
  },
  {
    cond: "rain",
    title: "Rain (Heavy, 50 mm/hr)",
    color: "#60a5fa",
    laser: "Hard block. Fog/rain droplets are comparable to laser wavelength — Mie scattering is catastrophic. The simulator treats heavy rain as a hard fog block for laser (>10 dB/km, availability gate). Laser WPT is not viable in rain.",
    microwave: "Best weather survival. ITU-R P.838-3: k=0.00454, α=1.244 at 5.8 GHz. Attenuation: 0.97 dB/km at 100 mm/hr, 0.44 dB/km at 50 mm/hr. At 5 km in heavy rain: only 2.2–4.8 dB loss from atmosphere — easily manageable.",
    decision: "Rain = microwave only (at ranges where geometric spread allows viable power delivery — typically <500 m for portable receivers, or fixed large-aperture rectennas at multi-km for infrastructure WPT).",
  },
  {
    cond: "haze",
    title: "Haze / Light Dust",
    color: "#facc15",
    laser: "Moderate impact. 0.5–2 dB/km depending on aerosol loading. At 2 km: 1–4 dB extra loss vs clear sky — efficiency drops ~30–60% relative. Still viable for tactical range.",
    microwave: "Essentially no impact. Sub-dB per km even in heavy industrial haze. Haze has negligible effect on 5.8 GHz.",
    decision: "Haze favors laser in most configurations — the geometric advantage of laser over microwave still dominates even with 2–4 dB atmospheric penalty.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Engineering solutions
// ─────────────────────────────────────────────────────────────────────────────

const SOLUTIONS = [
  {
    title: "Relay-Regeneration Architecture",
    status: "Aether core IP — no prior art for terrestrial power relay",
    gain: "+20–40 dB over direct link in smoke at 5 km",
    cost: "~$50k/relay drone node + $5k EDFA",
    trl: "TRL 3–4 (concept validated, component-level demo needed)",
    detail: `Instead of a single 5 km link, split into N×1 km hops. Each relay drone receives laser power, converts to electrical, buffers briefly, then retransmits from a fresh, bright source. Loss resets at each node — you never accumulate 40 dB of smoke attenuation. The physics ceiling per hop is the same as a 1 km link: ~12–18% single-hop efficiency, multiplied N times minus relay conversion overhead.

End-to-end math: 5 hops × (1 − 0.15 relay overhead) × 0.12 single-hop eff = 0.85^5 × 0.12 = 5.4%.
That is 300–500 W delivered at 5 km in smoke, versus ~0 W direct.`,
  },
  {
    title: "Adaptive Optics (AO)",
    status: "Commercially available; DoD-proven for laser comm/weapons",
    gain: "+4 to +12 dB at 2–5 km range (2.5–16× Strehl improvement)",
    cost: "$50k–$200k per system (MEMS DM + wavefront sensor)",
    trl: "TRL 7–8 for AO systems; TRL 5–6 for WPT integration",
    detail: `A Shack-Hartmann wavefront sensor measures the distorted wavefront at the receiver (or a guide star). A deformable mirror (MEMS, 140–1020 actuators) in the transmitter path applies the conjugate phase — pre-compensating for the turbulence the beam will encounter.

Strehl gain at 2 km: 3% open-loop → 50–75% corrected (2.5–10× gain in power on target).
Strehl gain at 5 km: <1% open-loop → 5–20% corrected (still 5–20× gain).
Bandwidth requirement: correction rate ≥ Greenwood frequency fG = 0.43(v/r₀)^(5/3) ≈ 20–100 Hz at tactical sites.
System size: compact MEMS-AO systems fit in a 0.3 m aperture head under 10 kg.`,
  },
  {
    title: "1550 nm Wavelength",
    status: "Eye-safe (IEC Class 1 above safe distance), telecom-grade components",
    gain: "−40% smoke extinction vs 1070 nm; −30 dB at 5 km in smoke",
    cost: "EDFA amplifiers: $2–5k each (commodity telecom). Fiber lasers: $15–50k.",
    trl: "TRL 7–8 for components; TRL 4 for WPT integration",
    detail: `The 1550 nm band is where the global telecom industry has concentrated 40 years of R&D. Erbium-doped fiber amplifiers (EDFA) are commodity items at $2–5k per unit. Fiber Bragg gratings, beam combiners, wavelength-selective couplers — all commercial off-the-shelf.

Smoke extinction coefficient at 1550 nm: ~4.8 dB/km vs 8 dB/km at 1070 nm.
Over 5 km smoke: 24 dB loss vs 40 dB loss — a 16 dB (40×) advantage.
Eye safety: MPE (Maximum Permissible Exposure) at 1550 nm is 1000× higher than at 1070 nm. Eye-safe for operator proximity.
NV invisibility: standard Gen 2/3 NV tubes sensitive to 600–900 nm only. 1550 nm is completely invisible to enemy night vision.`,
  },
  {
    title: "InP Monochromatic PV Cells",
    status: "Lab-demonstrated 55%; commercializing 2025–2026 (Sandia, Alta Devices)",
    gain: "+12 percentage points conversion efficiency (43% actual → 55% InP)",
    cost: "$50–200/cm² at present; volume production expected to reduce to $5–20/cm²",
    trl: "TRL 5–6 (single-cell demonstrated; module-level in progress)",
    detail: `Standard PV cells convert broadband sunlight at 20–25% efficiency. Monochromatic PV cells are optimized for a single laser wavelength — bandgap matched to photon energy. At 1070 nm: GaAs cells achieve 45–50%. At 1550 nm: InP cells achieve 50–55% (Sandia 2023).

Current simulator: 50% PV base × 86% temperature derating = 43% actual PV efficiency.
Upgrade to InP: 55% actual → +28% relative efficiency improvement.
Example: 2 km clear sky, 15 kW target — current: 8.2% sys efficiency. With InP: 12.6% sys efficiency.
Weight impact: smaller PV area needed for same power → lighter receiver (UAV payload benefit).`,
  },
  {
    title: "Larger Transmit Aperture",
    status: "Straightforward engineering; size/weight trade",
    gain: "+6 dB per 2× aperture diameter (+12 dB for 4× aperture)",
    cost: "Telescope cost scales roughly as D^2.5; 2× aperture ~5–7× cost increase",
    trl: "TRL 9 (off-the-shelf telescopes); TRL 6 for beam quality at WPT power levels",
    detail: `The laser beam divergence angle θ = λ/D. Doubling aperture D halves θ, meaning the beam is 2× smaller at range → 4× more power captured by fixed receiver (6 dB gain).

0.3 m aperture → 15 mm beam at 2 km.
0.6 m aperture → 7.5 mm beam at 2 km (4× power collected).
1.0 m aperture → 4.5 mm beam at 2 km (11× power collected vs 0.3 m).

Practical limits: (1) pointing accuracy — larger aperture at same jitter means larger miss distance; (2) thermal loading — high-power beams induce wavefront distortion in large optics; (3) weight — 1 m telescope + mount ~80–150 kg (vehicle-mounted only).

Optimal for fixed installations (FOB to FOB power). For mobile tactical use, 0.3–0.5 m is the practical sweet spot.`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

export default function SweepPage() {
  const [mode, setMode] = useState<"laser" | "microwave">("laser");
  const [powerKw, setPowerKw] = useState(15);
  const [laserData, setLaserData] = useState<SweepPoint[]>([]);
  const [mwData, setMwData] = useState<SweepPoint[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"regimes" | "losses" | "conditions" | "solutions">("regimes");
  const [expandedSolution, setExpandedSolution] = useState<number | null>(null);
  const [showTable, setShowTable] = useState(false);
  const [selectedPreset, setSelectedPreset] = useState<SweepPreset | null>(null);
  const [showAllConditions, setShowAllConditions] = useState(false);
  const [yMetric, setYMetric] = useState<"system_eff_pct" | "dc_power_kw" | "fuel_saved_l_day">("system_eff_pct");
  const [comparePowerKw, setComparePowerKw] = useState<number | null>(null);
  const [compareLaserData, setCompareLaserData] = useState<SweepPoint[]>([]);
  const [compareMwData, setCompareMwData] = useState<SweepPoint[]>([]);
  const [loadingCompare, setLoadingCompare] = useState(false);

  const runSweep = useCallback(async (m: "laser" | "microwave", p: number) => {
    setLoading(true);
    setError(null);
    try {
      const [laser, mw] = await Promise.all([
        sweep("laser", p),
        sweep("microwave", p),
      ]);
      setLaserData(laser);
      setMwData(mw);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  const runCompare = useCallback(async (p: number) => {
    setLoadingCompare(true);
    try {
      const [laser, mw] = await Promise.all([
        sweep("laser", p),
        sweep("microwave", p),
      ]);
      setCompareLaserData(laser);
      setCompareMwData(mw);
    } catch {
      // silent — compare is best-effort
    } finally {
      setLoadingCompare(false);
    }
  }, []);

  // Auto-run on load
  const didInitRef = React.useRef(false);
  useEffect(() => {
    didInitRef.current = true;
    runSweep("laser", powerKw);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Debounced auto-re-run when powerKw changes (after initial load)
  useEffect(() => {
    if (!didInitRef.current) return;
    const timer = setTimeout(() => {
      runSweep("laser", powerKw);
      if (comparePowerKw !== null) runCompare(comparePowerKw);
    }, 600);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [powerKw]);

  const chartData = useMemo(() => {
    const byRange: Record<number, PivotRow> = {};
    const addPts = (pts: SweepPoint[], prefix: string) => {
      for (const pt of pts) {
        if (!byRange[pt.range_km]) byRange[pt.range_km] = { range_km: pt.range_km };
        const val = pt[yMetric];
        if (val != null && !isNaN(val as number)) {
          byRange[pt.range_km][`${prefix}${pt.condition}`] = parseFloat((val as number).toFixed(4));
        }
      }
    };
    addPts(laserData, "laser_");
    addPts(mwData, "mw_");
    if (comparePowerKw !== null) {
      addPts(compareLaserData, "cmp_laser_");
      addPts(compareMwData, "cmp_mw_");
    }
    return Object.values(byRange).sort((a, b) => a.range_km - b.range_km);
  }, [laserData, mwData, compareLaserData, compareMwData, comparePowerKw, yMetric]);

  const allLines = useMemo(() => {
    const laserConditions = laserData.length ? Array.from(new Set(laserData.map(p => p.condition))) : [];
    const mwConditions = mwData.length ? Array.from(new Set(mwData.map(p => p.condition))) : [];
    const cmpLaserConditions = compareLaserData.length ? Array.from(new Set(compareLaserData.map(p => p.condition))) : [];
    const cmpMwConditions = compareMwData.length ? Array.from(new Set(compareMwData.map(p => p.condition))) : [];

    // In simple mode: only the 3 most important lines
    const KEY_CONDITIONS = { laser: ["clear", "smoke"], mw: ["clear"] };

    const laserToShow = showAllConditions ? laserConditions : laserConditions.filter(c => KEY_CONDITIONS.laser.includes(c));
    const mwToShow = showAllConditions ? mwConditions : mwConditions.filter(c => KEY_CONDITIONS.mw.includes(c));

    return [
      ...laserToShow.map(c => ({
        key: `laser_${c}`,
        label: showAllConditions ? `Laser — ${CONDITION_META[c]?.label ?? c}` : (c === "clear" ? "Laser (clear sky)" : "Laser (smoke)"),
        color: CONDITION_META[c]?.color ?? "#888", dash: CONDITION_META[c]?.dash, strokeWidth: 2.5, opacity: 1,
      })),
      ...mwToShow.map(c => ({
        key: `mw_${c}`,
        label: showAllConditions ? `μWave — ${CONDITION_META[c]?.label ?? c}` : "Microwave (clear sky)",
        color: "#a78bfa", dash: "8 4", strokeWidth: 1.5, opacity: 0.8,
      })),
      ...(comparePowerKw !== null ? (showAllConditions ? cmpLaserConditions : cmpLaserConditions.filter(c => KEY_CONDITIONS.laser.includes(c))).map(c => ({
        key: `cmp_laser_${c}`, label: `Laser — ${CONDITION_META[c]?.label ?? c} (${comparePowerKw}kW ◈)`,
        color: CONDITION_META[c]?.color ?? "#888", dash: "4 3", strokeWidth: 1.5, opacity: 0.45,
      })) : []),
      ...(comparePowerKw !== null ? (showAllConditions ? cmpMwConditions : cmpMwConditions.filter(c => KEY_CONDITIONS.mw.includes(c))).map(c => ({
        key: `cmp_mw_${c}`, label: `μWave — ${CONDITION_META[c]?.label ?? c} (${comparePowerKw}kW ◈)`,
        color: "#a78bfa", dash: "2 4", strokeWidth: 1, opacity: 0.3,
      })) : []),
    ];
  }, [laserData, mwData, compareLaserData, compareMwData, comparePowerKw, powerKw, showAllConditions]);

  const hasData = laserData.length > 0 || mwData.length > 0;
  const laserConditions = useMemo(() => laserData.length ? Array.from(new Set(laserData.map(p => p.condition))) : [], [laserData]);
  const mwConditions = useMemo(() => mwData.length ? Array.from(new Set(mwData.map(p => p.condition))) : [], [mwData]);

  return (
    <div
      className="max-w-6xl mx-auto px-4 py-8 space-y-8"
      style={{ color: "var(--text)" }}
    >
      {/* ── Header ── */}
      <div>
        <div className="text-xs uppercase tracking-widest mb-1" style={{ color: "var(--text-subtle)" }}>
          Physics Deep Dive
        </div>
        <h1 className="text-2xl font-bold" style={{ color: "var(--text)" }}>
          Range Sweep Analysis
        </h1>
        <p className="mt-1 text-sm" style={{ color: "var(--text-muted)" }}>
          How system efficiency degrades with distance — the physics, the math, and the engineering fixes.
          All conditions computed simultaneously. Laser and microwave overlaid.
        </p>
      </div>

      {/* ── Use-case presets ── */}
      <div>
        <div className="text-xs uppercase tracking-wider mb-3" style={{ color: "var(--text-subtle)" }}>
          Use Case Presets — click to pin an operating point on the chart
        </div>
        <div className="flex gap-2 overflow-x-auto pb-2" style={{ scrollbarWidth: "thin" }}>
          {SWEEP_PRESETS.map((p) => {
            const active = selectedPreset?.id === p.id;
            return (
              <button
                key={p.id}
                onClick={() => {
                  if (active) {
                    setSelectedPreset(null);
                  } else {
                    setSelectedPreset(p);
                    setPowerKw(p.power_kw);
                    setActiveTab("regimes");
                  }
                }}
                className="flex-shrink-0 text-left rounded-xl px-3 py-2.5 transition-all"
                style={
                  active
                    ? { background: "var(--accent-dim)", border: "1px solid var(--accent)" }
                    : { background: "var(--surface)", border: "1px solid var(--border)" }
                }
              >
                <div className="text-xs font-semibold" style={{ color: active ? "var(--accent)" : "var(--text)" }}>
                  {p.label}
                </div>
                <div className="text-[10px] mt-0.5 font-mono" style={{ color: "var(--text-muted)" }}>
                  {p.sublabel}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Controls ── */}
      <Card>
        <div className="flex flex-wrap gap-6 items-end">
          <div>
            <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>
              Power Target
            </div>
            <div className="flex items-center gap-3">
              <input
                type="range"
                min={0.1}
                max={50}
                step={0.1}
                value={powerKw}
                onChange={(e) => { setPowerKw(Number(e.target.value)); setSelectedPreset(null); }}
                className="w-40"
                style={{ accentColor: "var(--accent)" }}
              />
              <span className="font-mono text-sm" style={{ color: "var(--text)" }}>{powerKw} kW</span>
            </div>
            <div className="text-xs mt-1" style={{ color: "var(--text-subtle)" }}>
              Drone ISR: 0.5 kW · Sensor: 0.1 kW · SOF: 3 kW · FOB: 15 kW · C-UAS: 10 kW
            </div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>
              Compare with power level
            </div>
            <div className="flex gap-1.5 flex-wrap">
              {[null, 0.5, 5, 15, 50].map((p) => {
                const active = comparePowerKw === p;
                const label = p === null ? "None" : `${p} kW`;
                return (
                  <button
                    key={String(p)}
                    onClick={() => {
                      setComparePowerKw(p);
                      if (p !== null && p !== powerKw) {
                        runCompare(p);
                      } else {
                        setCompareLaserData([]);
                        setCompareMwData([]);
                      }
                    }}
                    className="px-2.5 py-1 rounded-lg text-xs font-medium transition-all"
                    style={
                      active
                        ? { background: "var(--accent-dim)", color: "var(--accent)", border: "1px solid var(--accent)" }
                        : { background: "var(--surface-2)", color: "var(--text-muted)", border: "1px solid var(--border)" }
                    }
                  >
                    {label}
                  </button>
                );
              })}
              {loadingCompare && (
                <span className="text-xs self-center animate-pulse" style={{ color: "var(--text-muted)" }}>loading…</span>
              )}
            </div>
            <div className="text-xs mt-1" style={{ color: "var(--text-subtle)" }}>
              Overlays a second sweep at faded opacity — faint lines show how power level shifts the curve
            </div>
          </div>

          <button
            onClick={() => runSweep(mode, powerKw)}
            disabled={loading}
            className="px-5 py-2 rounded-lg text-sm font-semibold transition-all"
            style={
              loading
                ? { background: "var(--surface-2)", color: "var(--text-subtle)" }
                : { background: "var(--accent)", color: "#fff" }
            }
          >
            {loading ? "Computing…" : "Re-run sweep"}
          </button>
          {loading && (
            <span className="text-xs animate-pulse" style={{ color: "var(--text-muted)" }}>
              Fetching all ranges × all conditions for laser + microwave…
            </span>
          )}
        </div>
      </Card>

      {error && (
        <div className="rounded-xl px-4 py-3 text-sm" style={{ background: "rgba(127,29,29,0.15)", border: "1px solid rgba(127,29,29,0.5)", color: "#fca5a5" }}>
          <strong>Error:</strong> {error}
        </div>
      )}

      {/* ── Preset callout ── */}
      {selectedPreset && (
        <div
          className="rounded-xl px-5 py-4"
          style={{ background: "var(--accent-dim)", border: "1px solid var(--accent)" }}
        >
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-xs uppercase tracking-wider mb-1" style={{ color: "var(--accent)" }}>
                Operating point — {selectedPreset.label}
              </div>
              <div className="font-mono text-sm mb-2" style={{ color: "var(--text)" }}>
                {selectedPreset.sublabel}
                {selectedPreset.nearField && (
                  <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded" style={{ background: "rgba(99,102,241,0.2)", color: "var(--accent)" }}>
                    near-field · off chart left
                  </span>
                )}
                {!selectedPreset.nearField && (
                  <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded" style={{ background: "rgba(99,102,241,0.2)", color: "var(--accent)" }}>
                    pinned on chart ↓
                  </span>
                )}
              </div>
              <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)", maxWidth: "60ch" }}>
                {selectedPreset.note}
              </p>
            </div>
            <button
              onClick={() => setSelectedPreset(null)}
              className="shrink-0 text-xs px-2 py-1 rounded"
              style={{ color: "var(--text-subtle)", border: "1px solid var(--border)" }}
            >
              clear
            </button>
          </div>
        </div>
      )}

      {/* ── Chart ── */}
      {hasData && (
        <Card>
          <div className="flex items-start justify-between gap-4 mb-4">
            <div className="flex-1 min-w-0">
              <div className="text-xs font-medium uppercase tracking-wider" style={{ color: "var(--text-subtle)" }}>
                {yMetric === "system_eff_pct" ? "System Efficiency (%) vs Range (km)"
                  : yMetric === "dc_power_kw" ? "DC Power Delivered (kW) vs Range (km)"
                  : "Fuel Saved (L/day) vs Range (km)"}
              </div>
              <p className="text-xs mt-1" style={{ color: "var(--text-muted)" }}>
                {showAllConditions ? "All atmospheric conditions." : "3 key curves: laser clear, laser smoke, microwave clear."}
                {comparePowerKw !== null && " Faded ◈ = comparison power level."}
              </p>
              {yMetric === "system_eff_pct" && (
                <p className="text-xs mt-1.5 px-2 py-1 rounded" style={{ background: "rgba(251,146,60,0.08)", border: "1px solid rgba(251,146,60,0.2)", color: "#fb923c" }}>
                  Efficiency % is power-independent — changing kW won&apos;t shift these curves. Switch to &quot;DC Power&quot; or &quot;Fuel Saved&quot; to see the power slider take effect.
                </p>
              )}
            </div>
            <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
              {/* Y-axis metric selector */}
              <div className="flex rounded-lg overflow-hidden" style={{ border: "1px solid var(--border)" }}>
                {([
                  { key: "system_eff_pct", label: "Efficiency %" },
                  { key: "dc_power_kw", label: "DC Power" },
                  { key: "fuel_saved_l_day", label: "Fuel Saved" },
                ] as const).map((m) => (
                  <button
                    key={m.key}
                    onClick={() => setYMetric(m.key)}
                    className="px-2.5 py-1 text-xs transition-all"
                    style={yMetric === m.key
                      ? { background: "var(--accent)", color: "#fff" }
                      : { background: "var(--surface-2)", color: "var(--text-muted)" }
                    }
                  >
                    {m.label}
                  </button>
                ))}
              </div>
              {comparePowerKw !== null && (
                <div className="text-xs px-2.5 py-1 rounded-lg font-mono" style={{ background: "var(--surface-2)", border: "1px solid var(--border)", color: "var(--text-muted)" }}>
                  {powerKw} kW vs <span style={{ color: "var(--accent)" }}>{comparePowerKw} kW ◈</span>
                </div>
              )}
              <button
                onClick={() => setShowAllConditions(!showAllConditions)}
                className="text-xs px-3 py-1 rounded-lg transition-all"
                style={showAllConditions
                  ? { background: "var(--surface-2)", color: "var(--text-muted)", border: "1px solid var(--border)" }
                  : { background: "var(--accent-dim)", color: "var(--accent)", border: "1px solid var(--accent)" }
                }
              >
                {showAllConditions ? "Simple view" : "All conditions"}
              </button>
            </div>
          </div>
          <ResponsiveContainer width="100%" height={420}>
            <LineChart data={chartData} margin={{ top: 8, right: 24, left: 16, bottom: 36 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e1e2a" />
              <XAxis
                dataKey="range_km"
                tick={{ fill: "#8888a0", fontSize: 11 }}
                tickLine={false}
                label={{ value: "Range (km)", position: "insideBottom", offset: -16, fill: "#55556a", fontSize: 11 }}
              />
              <YAxis
                tick={{ fill: "#8888a0", fontSize: 11 }}
                tickLine={false}
                width={52}
                label={{
                  value: yMetric === "system_eff_pct" ? "Efficiency (%)" : yMetric === "dc_power_kw" ? "DC Power (kW)" : "Fuel (L/day)",
                  angle: -90, position: "insideLeft", dx: -6, fill: "#55556a", fontSize: 10
                }}
              />
              <Tooltip
                contentStyle={{ background: "#111118", border: "1px solid #252530", borderRadius: 10, fontSize: 11, color: "#f0f0f5", padding: "8px 12px" }}
                labelFormatter={(v) => `Range: ${v} km`}
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                formatter={(v: any) => {
                  if (typeof v !== "number") return ["—"];
                  if (yMetric === "system_eff_pct") return [`${v.toFixed(3)}%`];
                  if (yMetric === "dc_power_kw") return [`${v.toFixed(3)} kW`];
                  return [`${v.toFixed(1)} L/day`];
                }}
                cursor={{ stroke: "#252548", strokeWidth: 1 }}
              />
              <Legend
                wrapperStyle={{ fontSize: 10, color: "#8888a0", paddingTop: 8 }}
                iconType="square"
                iconSize={8}
              />

              {/* Regime reference lines — labels at insideBottom to avoid crowding at top */}
              <ReferenceLine x={0.5} stroke="#252540" strokeDasharray="6 3">
                <Label value="500m" position="insideBottomRight" style={{ fontSize: 9, fill: "#44445a" }} />
              </ReferenceLine>
              <ReferenceLine x={2.0} stroke="#252540" strokeDasharray="6 3">
                <Label value="2km" position="insideBottomRight" style={{ fontSize: 9, fill: "#44445a" }} />
              </ReferenceLine>
              <ReferenceLine x={5.0} stroke="#303020" strokeDasharray="4 4">
                <Label value="5km relay" position="insideBottomRight" style={{ fontSize: 9, fill: "#505030" }} />
              </ReferenceLine>
              {yMetric === "system_eff_pct" && (
                <ReferenceLine y={1} stroke="#1e1e2a" strokeDasharray="2 6">
                  <Label value="1% min" position="insideRight" style={{ fontSize: 9, fill: "#44445a" }} />
                </ReferenceLine>
              )}

              {/* Selected preset pin */}
              {selectedPreset && !selectedPreset.nearField && (
                <ReferenceLine x={selectedPreset.range_km} stroke="#6366f1" strokeWidth={1.5}>
                  <Label value={`▼ ${selectedPreset.label}`} position="insideTopRight" style={{ fontSize: 10, fill: "#6366f1", fontWeight: 600 }} />
                </ReferenceLine>
              )}

              {allLines.map((l) => (
                <Line
                  key={l.key}
                  type="monotone"
                  dataKey={l.key}
                  name={l.label}
                  stroke={l.color}
                  strokeWidth={l.strokeWidth}
                  strokeDasharray={l.dash}
                  strokeOpacity={l.opacity}
                  dot={false}
                  activeDot={{ r: 3, strokeWidth: 0 }}
                  connectNulls={false}
                  isAnimationActive={false}
                />
              ))}
            </LineChart>
          </ResponsiveContainer>

          {/* Quick takeaways below chart */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-5">
            {[
              { label: "Laser dominates", text: "Clear sky, >200m — beam divergence asymmetry makes this unambiguous" },
              { label: "Microwave survives rain", text: "Laser hard-blocks in rain/fog; microwave loses <2 dB/km at 50 mm/hr at 5.8 GHz" },
              { label: "Both fail at 5km+ (direct)", text: "Relay-regeneration is the only viable path for multi-km degraded conditions" },
            ].map((t) => (
              <div key={t.label} className="rounded-lg px-3 py-2.5 text-xs" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
                <div className="font-semibold mb-0.5" style={{ color: "var(--accent)" }}>{t.label}</div>
                <div style={{ color: "var(--text-muted)" }}>{t.text}</div>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* ── Deep dive tabs ── */}
      <div>
        <div className="flex gap-1 mb-4 flex-wrap">
          {(["regimes", "losses", "conditions", "solutions"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className="px-4 py-1.5 rounded-lg text-xs font-medium uppercase tracking-wider transition-all"
              style={
                activeTab === tab
                  ? { background: "var(--accent)", color: "#fff" }
                  : { background: "var(--surface)", color: "var(--text-muted)", border: "1px solid var(--border)" }
              }
            >
              {tab === "regimes" ? "Range Regimes" : tab === "losses" ? "Loss Mechanisms" : tab === "conditions" ? "By Condition" : "Engineering Fixes"}
            </button>
          ))}
        </div>

        {/* REGIMES TAB */}
        {activeTab === "regimes" && (
          <div className="space-y-4">
            <p className="text-sm" style={{ color: "var(--text-muted)" }}>
              Four distinct physics regimes emerge from the range sweep. Each regime has different dominant loss mechanisms, different viable technologies, and different engineering responses.
            </p>
            {REGIMES.map((r, idx) => {
              const isActive = selectedPreset?.regimeIdx === idx;
              return (
              <div key={r.range} className="rounded-xl" style={isActive ? { outline: "2px solid var(--accent)", outlineOffset: "-2px" } : {}}>
              <Card>
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <span
                      className="text-xs font-mono font-bold px-2 py-0.5 rounded mr-2"
                      style={{ background: r.color + "20", color: r.color, border: `1px solid ${r.color}40` }}
                    >
                      {r.range}
                    </span>
                    <span className="font-semibold text-sm" style={{ color: "var(--text)" }}>{r.label}</span>
                  </div>
                  <span className="text-xs px-2 py-0.5 rounded shrink-0" style={{ background: "var(--surface-2)", color: "var(--text-muted)", border: "1px solid var(--border)" }}>
                    {r.badge}
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-subtle)" }}>Physics problems at this range</div>
                    <ul className="space-y-1">
                      {r.problems.map((p, i) => (
                        <li key={i} className="text-xs flex gap-2" style={{ color: "var(--text-muted)" }}>
                          <span style={{ color: "#f97316" }}>—</span>
                          {p}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-subtle)" }}>Quantified math</div>
                    <ul className="space-y-1">
                      {r.math.map((m, i) => (
                        <li key={i} className="text-xs font-mono" style={{ color: "var(--text-muted)", lineHeight: 1.6 }}>
                          {m}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                <div className="mb-3">
                  <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-subtle)" }}>Engineering fixes</div>
                  <div className="flex flex-wrap gap-2">
                    {r.solutions.map((s, i) => (
                      <div key={i} className="rounded-lg px-3 py-1.5 text-xs" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
                        <span className="font-medium" style={{ color: "var(--accent)" }}>{s.fix}</span>
                        <span style={{ color: "var(--text-muted)" }}> → {s.gain}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="text-xs" style={{ color: "var(--text-subtle)" }}>
                  <span className="font-medium" style={{ color: "var(--text-muted)" }}>Applications: </span>
                  {r.applications}
                </div>
                {isActive && selectedPreset && (
                  <div className="mt-3 pt-3 flex items-start gap-2" style={{ borderTop: "1px solid var(--accent)", opacity: 0.9 }}>
                    <span className="text-xs px-2 py-0.5 rounded font-medium shrink-0" style={{ background: "var(--accent-dim)", color: "var(--accent)", border: "1px solid var(--accent)" }}>
                      {selectedPreset.label}
                    </span>
                    <span className="text-xs" style={{ color: "var(--text-muted)" }}>
                      {selectedPreset.note}
                    </span>
                  </div>
                )}
              </Card>
              </div>
              );
            })}
          </div>
        )}

        {/* LOSS MECHANISMS TAB */}
        {activeTab === "losses" && (
          <div className="space-y-4">
            <p className="text-sm" style={{ color: "var(--text-muted)" }}>
              Every point of efficiency lost in the system can be attributed to one of four loss mechanisms. Understanding which mechanism dominates at your operating point is the key to improving performance.
            </p>
            {LOSS_MECHANISMS.map((lm) => (
              <Card key={lm.title}>
                <div className="flex items-center gap-3 mb-4">
                  <span className="text-xl" style={{ color: lm.color }}>{lm.icon}</span>
                  <span className="font-semibold" style={{ color: "var(--text)" }}>{lm.title}</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-1.5" style={{ color: "var(--text-subtle)" }}>Laser</div>
                    <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>{lm.laser}</p>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-1.5" style={{ color: "var(--text-subtle)" }}>Microwave</div>
                    <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>{lm.microwave}</p>
                  </div>
                </div>
                <div className="rounded-lg px-3 py-2 mb-3" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
                  <div className="text-xs uppercase tracking-wider mb-1" style={{ color: "var(--text-subtle)" }}>Formula</div>
                  <pre className="text-xs font-mono whitespace-pre-wrap" style={{ color: "#fb923c" }}>{lm.formula}</pre>
                </div>
                <div>
                  <div className="text-xs uppercase tracking-wider mb-1" style={{ color: "var(--text-subtle)" }}>How to fix it</div>
                  <p className="text-xs" style={{ color: "var(--text-muted)" }}>{lm.fix}</p>
                </div>
              </Card>
            ))}
            {/* Total chain math */}
            <Card>
              <SectionHeader>Total Efficiency Chain — Worked Example</SectionHeader>
              <div className="space-y-3">
                {[
                  {
                    scenario: "Laser · 2 km · Clear · 15 kW target",
                    chain: [
                      { step: "Wall-plug → photon (laser)", value: "50%", db: "−3.0 dB" },
                      { step: "Atmospheric absorption (clear, 2 km)", value: "98%", db: "−0.08 dB" },
                      { step: "Turbulence Strehl (Cn² = 10⁻¹⁴, daytime)", value: "3–15%", db: "−8 to −15 dB" },
                      { step: "Pointing jitter (5 µrad at 2 km)", value: "85%", db: "−0.7 dB" },
                      { step: "Geometric beam capture (0.3 m aperture)", value: "98%", db: "−0.08 dB" },
                      { step: "Monochromatic PV conversion (50% base × 86% derating)", value: "43%", db: "−3.7 dB" },
                      { step: "Total (worst turbulence)", value: "≈ 0.4%", db: "−24 dB" },
                      { step: "Total (best turbulence)", value: "≈ 6–10%", db: "−10 to −12 dB" },
                    ],
                  },
                  {
                    scenario: "Microwave · 2 km · Clear · 15 kW target",
                    chain: [
                      { step: "Wall-plug → RF (GaN PA)", value: "55%", db: "−2.6 dB" },
                      { step: "Atmospheric (clear, 5.8 GHz)", value: "99.9%", db: "−0.004 dB" },
                      { step: "Geometric beam spread (0.83 m array)", value: "0.005%", db: "−43 dB" },
                      { step: "Rectenna efficiency (low power density)", value: "20–50%", db: "−3 to −7 dB" },
                      { step: "Total", value: "≈ 0.01%", db: "−40 dB" },
                    ],
                  },
                ].map((ex) => (
                  <div key={ex.scenario}>
                    <div className="text-xs font-semibold mb-2" style={{ color: "var(--text)" }}>{ex.scenario}</div>
                    <div className="rounded-lg overflow-hidden" style={{ border: "1px solid var(--border)" }}>
                      {ex.chain.map((row, i) => (
                        <div
                          key={i}
                          className="flex justify-between items-center px-3 py-1.5 text-xs"
                          style={{ borderBottom: i < ex.chain.length - 1 ? "1px solid var(--border)" : undefined, background: i % 2 === 0 ? "var(--surface)" : "var(--surface-2)" }}
                        >
                          <span style={{ color: "var(--text-muted)" }}>{row.step}</span>
                          <span className="font-mono flex gap-4">
                            <span style={{ color: row.db.startsWith("−") ? "#fb923c" : "var(--green)" }}>{row.db}</span>
                            <span style={{ color: "var(--text)" }}>{row.value}</span>
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        )}

        {/* CONDITIONS TAB */}
        {activeTab === "conditions" && (
          <div className="space-y-4">
            <p className="text-sm" style={{ color: "var(--text-muted)" }}>
              Each atmospheric condition creates a different dominant loss mode. The optimal technology choice depends on the mission's expected atmospheric environment.
            </p>
            {CONDITION_DEEP_DIVE.map((cd) => (
              <Card key={cd.cond}>
                <div className="flex items-center gap-3 mb-4">
                  <div
                    className="w-2 h-8 rounded-full shrink-0"
                    style={{ background: cd.color }}
                  />
                  <span className="font-semibold" style={{ color: "var(--text)" }}>{cd.title}</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-3">
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-1.5" style={{ color: "var(--text-subtle)" }}>Laser performance</div>
                    <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>{cd.laser}</p>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-wider mb-1.5" style={{ color: "var(--text-subtle)" }}>Microwave performance</div>
                    <p className="text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>{cd.microwave}</p>
                  </div>
                </div>
                <div className="rounded-lg px-3 py-2 text-xs" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
                  <span className="font-medium" style={{ color: "var(--accent)" }}>Recommended mode: </span>
                  <span style={{ color: "var(--text-muted)" }}>{cd.decision}</span>
                </div>
              </Card>
            ))}
            {/* Quick mode-selection decision matrix */}
            <Card>
              <SectionHeader>Mode Selection Decision Matrix</SectionHeader>
              <div className="rounded-lg overflow-hidden" style={{ border: "1px solid var(--border)" }}>
                {[
                  { range: "0 – 200 m", clear: "Laser or Microwave", smoke: "Microwave", rain: "Microwave", note: "Near-field; both viable" },
                  { range: "200 – 500 m", clear: "Laser", smoke: "Microwave", rain: "Microwave", note: "Laser efficiency >>>" },
                  { range: "500 m – 2 km", clear: "Laser", smoke: "Microwave (short); relay (long)", rain: "Microwave (fixed infra)", note: "Laser dominates clear sky" },
                  { range: "2 – 5 km", clear: "Laser (AO needed)", smoke: "Relay chain required", rain: "Not practical (mobile)", note: "Relay threshold" },
                  { range: "5 – 10 km", clear: "Relay chain only", smoke: "Relay chain only", rain: "Not practical", note: "Multi-hop required" },
                ].map((row, i) => (
                  <div
                    key={i}
                    className="grid grid-cols-5 text-xs px-3 py-2"
                    style={{ borderBottom: i < 4 ? "1px solid var(--border)" : undefined, background: i % 2 === 0 ? "var(--surface)" : "var(--surface-2)" }}
                  >
                    <span className="font-mono font-bold" style={{ color: "var(--text)" }}>{row.range}</span>
                    <span style={{ color: "#4ade80" }}>{row.clear}</span>
                    <span style={{ color: "#f97316" }}>{row.smoke}</span>
                    <span style={{ color: "#60a5fa" }}>{row.rain}</span>
                    <span style={{ color: "var(--text-muted)" }}>{row.note}</span>
                  </div>
                ))}
                <div className="grid grid-cols-5 text-xs px-3 py-1.5" style={{ background: "var(--surface-2)", borderTop: "1px solid var(--border)" }}>
                  {["Range", "Clear sky", "Smoke", "Rain", "Note"].map((h) => (
                    <span key={h} className="uppercase tracking-wider text-[10px]" style={{ color: "var(--text-subtle)" }}>{h}</span>
                  ))}
                </div>
              </div>
            </Card>
          </div>
        )}

        {/* SOLUTIONS TAB */}
        {activeTab === "solutions" && (
          <div className="space-y-3">
            <p className="text-sm" style={{ color: "var(--text-muted)" }}>
              Five engineering interventions address the primary loss mechanisms. Each is quantified by efficiency gain, cost, and technology readiness level (TRL 1–9).
            </p>
            {SOLUTIONS.map((s, i) => (
              <Card key={i}>
                <div
                  className="cursor-pointer"
                  onClick={() => setExpandedSolution(expandedSolution === i ? null : i)}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <div className="font-semibold text-sm mb-1" style={{ color: "var(--text)" }}>{s.title}</div>
                      <div className="text-xs" style={{ color: "var(--text-muted)" }}>{s.status}</div>
                    </div>
                    <span className="text-sm" style={{ color: "var(--text-subtle)" }}>{expandedSolution === i ? "▲" : "▼"}</span>
                  </div>
                  <div className="grid grid-cols-3 gap-3 mt-3">
                    {[
                      { label: "Efficiency gain", value: s.gain, color: "#22c55e" },
                      { label: "Cost estimate", value: s.cost, color: "#facc15" },
                      { label: "TRL", value: s.trl, color: "var(--accent)" },
                    ].map((m) => (
                      <div key={m.label} className="rounded-lg px-3 py-2" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
                        <div className="text-[10px] uppercase tracking-wider mb-0.5" style={{ color: "var(--text-subtle)" }}>{m.label}</div>
                        <div className="text-xs font-medium" style={{ color: m.color }}>{m.value}</div>
                      </div>
                    ))}
                  </div>
                </div>
                {expandedSolution === i && (
                  <div className="mt-4 pt-4 text-xs leading-relaxed whitespace-pre-line" style={{ color: "var(--text-muted)", borderTop: "1px solid var(--border)" }}>
                    {s.detail}
                  </div>
                )}
              </Card>
            ))}
            {/* Combined upgrade scenario */}
            <Card>
              <SectionHeader>Combined Upgrade Scenario — Best Realistic Build-Out</SectionHeader>
              <p className="text-xs mb-4" style={{ color: "var(--text-muted)" }}>
                Stack all viable improvements simultaneously. Starting from the current baseline (laser · 2 km · clear · 15 kW target):
              </p>
              <div className="space-y-1">
                {[
                  { step: "Baseline (current simulator)", eff: "6–10%", delta: "" },
                  { step: "+ 1550 nm wavelength (AO-compatible EDFA system)", eff: "7–12%", delta: "+1–2 pts (lower atm loss + better AO response)" },
                  { step: "+ Adaptive optics (2.5× Strehl improvement)", eff: "15–28%", delta: "+8–16 pts (dominant gain at 2 km)" },
                  { step: "+ InP PV cells (43% actual → 47% InP, 1.10× gain)", eff: "17–31%", delta: "+1–3 pts (modest — base GaAs already optimized at 50%)" },
                  { step: "+ Larger aperture (2× area, tighter beam)", eff: "23–29%", delta: "+4–8 pts (range-dependent cap limits gain at 2 km)" },
                  { step: "Total best-case (lab conditions, pre-dawn, low Cn²)", eff: "25–35%", delta: "Range-dependent cap: 29% @ 2 km, 19% @ 8.6 km" },
                  { step: "Total realistic fielded (daytime, moderate turbulence)", eff: "15–25%", delta: "DARPA PRAD 2025 anchor: ~20% real-world @ 8.6 km" },
                ].map((row, i) => (
                  <div
                    key={i}
                    className="flex justify-between items-center px-3 py-1.5 rounded-lg text-xs"
                    style={{
                      background: i === 0 ? "var(--surface-2)" : i === 6 ? "rgba(99,102,241,0.08)" : "transparent",
                      border: i === 6 ? "1px solid rgba(99,102,241,0.3)" : "1px solid transparent",
                    }}
                  >
                    <span style={{ color: "var(--text-muted)" }}>{row.step}</span>
                    <span className="font-mono font-semibold shrink-0 ml-4" style={{ color: i === 0 ? "#f97316" : i === 6 ? "var(--accent)" : "var(--green)" }}>{row.eff}</span>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        )}
      </div>

      {/* ── Data table (collapsed) ── */}
      {hasData && (
        <Card>
          <button
            onClick={() => setShowTable(!showTable)}
            className="w-full flex justify-between items-center text-xs"
            style={{ color: "var(--text-muted)" }}
          >
            <span className="uppercase tracking-wider font-medium">Raw sweep data — all ranges × all conditions</span>
            <span style={{ color: "var(--text-subtle)" }}>{showTable ? "▲ hide" : "▼ show"}</span>
          </button>
          {showTable && (
            <div className="mt-4 overflow-auto">
              {[
                { label: "Laser", data: laserData, conditions: laserConditions },
                { label: "Microwave", data: mwData, conditions: mwConditions },
              ].map(({ label, data, conditions }) => {
                if (!data.length) return null;
                const { rows } = pivotData(data);
                return (
                  <div key={label} className="mb-6">
                    <div className="text-xs uppercase tracking-wider mb-2" style={{ color: "var(--text-subtle)" }}>{label}</div>
                    <table className="w-full text-xs font-mono">
                      <thead>
                        <tr style={{ borderBottom: "1px solid var(--border)" }}>
                          <th className="text-left pb-1.5 pr-4" style={{ color: "var(--text-muted)" }}>km</th>
                          {conditions.map((c) => (
                            <th key={c} className="text-left pb-1.5 pr-4" style={{ color: CONDITION_META[c]?.color ?? "#888" }}>
                              {c}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {rows.map((row, i) => (
                          <tr key={i} style={{ borderBottom: "1px solid var(--border)" }}>
                            <td className="py-1 pr-4" style={{ color: "var(--text)" }}>{row.range_km}</td>
                            {conditions.map((c) => (
                              <td key={c} className="py-1 pr-4" style={{ color: row[c] != null && row[c] > 0 ? "var(--text-muted)" : "#55556a" }}>
                                {row[c] != null ? `${(row[c] as number).toFixed(2)}%` : "—"}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                );
              })}
            </div>
          )}
        </Card>
      )}


    </div>
  );
}
